### ISSUE TITLE
Add correct version for `phpmd`

### ISSUE THREAD

**Issue by inyono** [wmde/MultiFeed#3]
`composer phpmd` does not output anything with the specified version `~2.3`. It works with version `1.5.0`, though. Maybe the config is for an older version?

**Comment by thiemowmde** [comment]
This config is for PHPMD 2.3+. You can tell because `allow-underscore-test` was not supported before.

**Comment by inyono** [comment]
Okay, my bad. Apparently, there are only some differences in the default rules used. E.g., it recognises methods not named using camelCase just fine if I put in an error deliberately.

**Comment by manicki** [comment]
Yes, no output from PHPMD means all good :)
